services:
  api:
    image: lautiar/passmanager:latest
    container_name: passmanager_api
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/instance
    environment:
      - FLASK_ENV=development
      - SENTRY_DSN=${SENTRY_DSN:-}
      - FERNET_KEY=${FERNET_KEY:-}

volumes:
  db_data:
 
